# Generated by Django 5.2.7 on 2025-10-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_daily',
            field=models.BooleanField(default=False),
        ),
    ]
